### PR TITLE
Correctly extract PR identifier for CircleCI builds

### PR DESCRIPTION
**Pull request by markelliot**

### CODE REVIEW

**Comment by markelliot** [comment]
Not super clear on why Cobertura isn't picking up results of ServiceInfoFactoryTest, but it seems to only hit the Travis branch even when running locally.

**Comment by kt3k** [comment]
Thanks for the contribution.

The change itself makes sense. Thanks.

The coverage reporter has been broken since the plugin switched to 2.0 ecosystem. ( I've been looking for alternatives but I haven't found one yet.)

**Comment by markelliot** [comment]
any thoughts when you might release this?

**Comment by kt3k** [comment]
Sorry for being late.

I've published this as v2.6.1 to maven and bintray!

**Pull request merged**
