### PR TITLE
Replace ghprbPullLink with ghprbPullId in ServiceInfoFactory.groovy

### PR DESCRIPTION
**Pull request by jettbow**
serviceInfo.servicePullRequest should be assigned as Id of a PR.

### CODE REVIEW

**Comment by kt3k** [comment]
Thanks for the contribution! The change makes sense to me. Can you update the test case for this class as well?

**Comment by jettbow** [comment]
Sure! Updated.

**Comment by jettbow** [comment]
@kt3k Fixed.

**Comment by kt3k** [comment]
Released as v2.8.2 https://plugins.gradle.org/plugin/com.github.kt3k.coveralls http://repo1.maven.org/maven2/org/kt3k/gradle/plugin/coveralls-gradle-plugin/2.8.2/

**Pull request merged**
