### PR TITLE
Add support for Drone CI

### PR DESCRIPTION
**Pull request by jvia**
see: https://docs.drone.io/pipeline/environment/reference/

### CODE REVIEW

**Comment by kt3k** [comment]
Thanks!
Can you add test case in `src/test/groovy/org/kt3k/gradle/plugin/coveralls/domain/ServiceInfoFactoryTest.groovy`?

**Comment by jvia** [comment]
Added a test case.

**Review by kt3k — APPROVED** [review]
@jvia Thanks! LGTM

**Comment by jvia** [comment]
Thanks for merging! Would you be able to cut a release?

**Comment by kt3k** [comment]
@jvia Released as v2.12.0! https://plugins.gradle.org/plugin/com.github.kt3k.coveralls

**Pull request merged**
