### PR TITLE
Adding Jenkins CI support and updating README

### PR DESCRIPTION
**Pull request by dallasgutauckis**
- Adds Jenkins CI support (push and pull request)
 - Updates README to show relevant environment variables for custom builds

### CODE REVIEW

**Comment by kt3k** [comment]
Really thanks for the enhancement and documentation!

I'll release it soon.

**Comment by dallasgutauckis** [comment]
My pleasure.

**Comment by kt3k** [comment]
Released this version as v2.2.0.

http://search.maven.org/#artifactdetails%7Corg.kt3k.gradle.plugin%7Ccoveralls-gradle-plugin%7C2.2.0%7Cjar
https://bintray.com/kt3k/gradle-plugins/coveralls-gradle-plugin/2.2.0/view

Thanks,

**Comment by dallasgutauckis** [comment]
Hey @kt3k I've noticed that this is not showing the right pull number in coveralls.io; I've tried both the direct link and the number. Any idea what the value is supposed to be for the servicePullRequest?

**Comment by kt3k** [comment]
https://coveralls.zendesk.com/hc/en-us/articles/201770395-Do-you-support-Circle-CI-pull-request-comments-
This post says it should be CircleCI's `CI_PULL_REQUEST` env var. I'm personally not using CircleCI, then I can't give an example at the moment, but I'll try to check it later.

**Comment by kt3k** [comment]
https://github.com/circleci/frontend/blob/master/resources/assets/docs/environment-variables.md#build-details
According to this doc, it should be the url of the pull request. Hmm strange...

**Comment by dallasgutauckis** [comment]
The original implementation uses the URL, but coveralls shows `"Pull #0"` and doesn't link to the correct PR when clicked either. This might need some input from the coveralls team.

**Pull request merged**
