### PR TITLE
Travis CI detection issue

### LINKED ISSUE #15: Better detection of travis-ci vs pro
Currently if there is an env variable for repo token, plugin assumes it is travis-pro. This is not entirely correct. Since I have some integration tests, I am sending jacoco reports from my computer, not from travis. For this I need the env variable to be set, and yet I am using travis-ci not pro.

### PR DESCRIPTION
**Pull request by Kevin-Lee**
This fixes #15.
It still requires some extra step (i.e. adding `CI_NAME=travis-ci`) yet it is easy and simple enough.

### CODE REVIEW

**Comment by Kevin-Lee** [comment]
I've just uploaded the fixed one to [my bintray repo](https://bintray.com/kevinlee/maven/coveralls-gradle-plugin) and it works. Now I can see Coveralls's test coverage results.

If you want to test it, add the following info accordingly in your `build.gradle`.
```gradle
buildscript {
  repositories {
    jcenter()
    mavenCentral()
    maven {
      url  "http://dl.bintray.com/kevinlee/maven"
    }
  }
  dependencies {
    classpath 'org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.3.2'
  }
}
```
I'll add tests for my changes soon.

**Comment by Kevin-Lee** [comment]
Done

**Comment by kt3k** [comment]
Thank you very much! Nice documentation :+1:

**Comment by kt3k** [comment]
Uploaded this version as v2.4.0 (maven-central & bintray).

https://bintray.com/kt3k/gradle-plugins/coveralls-gradle-plugin/2.4.0/view

**Comment by Kevin-Lee** [comment]
@kt3k That's good. :+1: Thank you! I've just tested, and it works well. I'll remove the one I uploaded to my bintray for testing.

**Comment by kt3k** [comment]
Thanks for testing! :smile:

**Pull request merged**
