### PR TITLE
added support for GitHub Actions

### LINKED ISSUE #98: GitHub Actions
This plugin does not recognize if it is being run inside [GitHub Actions](https://github.com/features/actions) and will therefore hit the following case:

https://github.com/kt3k/coveralls-gradle-plugin/blob/09a14ecc12bcf32832aa0aaf00c8914d62ec7d44/src/main/groovy/org/kt3k/gradle/plugin/coveralls/domain/ServiceInfoFactory.groovy#L98-L107

For a start, consider the following two docs:
- [Default Environment Variables](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables#default-environment-variables)
- [Contexts](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#contexts)

For example, to check for GitHub Actions, you can use:
```groovy
private static boolean envIsGithubActions(Map<String, String> env) {
   env.get('GITHUB_ACTIONS') == 'true'
}
```

To get more information, especially about associated PRs, you will have to inspect the file pointed at by the envvar `GITHUB_EVENT_PATH`, like here: https://github.com/actions/toolkit/blob/99d3ad0a6473e7e7906681627a450150a772ee1d/packages/github/src/context.ts#L24-L29

### PR DESCRIPTION
**Pull request by musketyr**
fixes #98

also upgraded JGit as applying the plugin is breaking a couple of other plugins

### CODE REVIEW

**Comment by musketyr** [comment]
thank you! can you please, also push the new version to BinTray? I can see the release on GitHub but the version is not present on BinTray yet.

**Comment by kt3k** [comment]
I published to gradle portal (probably backed by bintray?). It seems taking some hours to be approved by gradle engineers.

```shellsession
$ ./gradlew publishPlugins

> Task :publishPlugins
Publishing plugin com.github.kt3k.coveralls version 2.9.0
Thank you. Your new plugin com.github.kt3k.coveralls has been submitted for approval by Gradle engineers. The request should be processed within the next 24 hours, at which point you will be contacted via email.
```

After the approval, it should appear on the plugin portal's page. https://plugins.gradle.org/plugin/com.github.kt3k.coveralls

**Comment by kt3k** [comment]
The new version has been released! https://plugins.gradle.org/plugin/com.github.kt3k.coveralls

**Comment by aalmiray** [comment]
@musketyr is referring to https://bintray.com/bintray/jcenter/org.kt3k.gradle.plugin%3Acoveralls-gradle-plugin

If you have never published to Bintray directly then these entries may be automatically mirrored form the Gradle Plugin portal after some time.

**Comment by kt3k** [comment]
> If you have never published to Bintray directly then these entries may be automatically mirrored form the Gradle Plugin portal after some time.

That's good to know. Thank you.

**Pull request merged**
