### PR TITLE
Fix compatibility with Gradle 7

### PR DESCRIPTION
**Pull request by melix**
In Gradle 7, task properties which are not annotated with an input annotation becomes an error.

This PR adds the missing annotations and adds test coverage for multiple Gradle versions.

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM. Thanks!

**Comment by chali** [comment]
I just hit this while working on Gradle 7 compatibility work. Any ETA when it could be released?

**Comment by chali** [comment]
@kt3k @melix thank you both for being on top of things!

**Comment by kt3k** [comment]
published as v2.11.0. Please let me know if something's wrong.

**Pull request merged**
