### PR TITLE
Pick up branch name from travis environment variable

### PR DESCRIPTION
**Pull request by andreldm**

### CODE REVIEW

**Comment by andreldm** [comment]
Thanks!

**Comment by kt3k** [comment]
Released as [v2.10.0](https://plugins.gradle.org/plugin/com.github.kt3k.coveralls)!

**Comment by andreldm** [comment]
Thanks for merging and issuing a release, but on which repository can I find this plugin published?

None of the below contain recent versions:
https://plugins.gradle.org/m2/org/kt3k/gradle/plugin/coveralls-gradle-plugin/
https://search.maven.org/artifact/org.kt3k.gradle.plugin/coveralls-gradle-plugin
https://bintray.com/kt3k/gradle-plugins/coveralls-gradle-plugin
https://bintray.com/bintray/jcenter/org.kt3k.gradle.plugin%3Acoveralls-gradle-plugin

**Comment by kt3k** [comment]
I only publish to gradle plugin portal these days. You should be able to use one of the following two examples.

```groovy
plugins {
  id "com.github.kt3k.coveralls" version "2.10.0"
}
```

(This is for older version of gradle)
```groovy
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.10.0"
  }
}

apply plugin: "com.github.kt3k.coveralls"
```

**Comment by andreldm** [comment]
Thanks again, it worked!

**Pull request merged**
